### PR TITLE
feat: add jokerace voting plugin

### PR DESCRIPTION
**Pull request by seanmc9**
TODOs:
- [x] figure out how to shoehorn `contractAddress` and `numVotes` into `packages/jokerace/src/JokeRace.ts`
- [x] fill out test files
- [x] update README

### CODE REVIEW

**Comment by seanmc9** [comment]
@Quazia so I've fiddled with things a bit and I think that if it could be possible to add a `contractAddress` parameter and a `numVotes` param (both of which should be pretty standard I believe - the contract that the vote txn is going to and the number of votes being cast) to the `VoteActionParams`, then we could make our `castVoteWithoutProof()` function work with y'all's!

**Comment by seanmc9** [comment]
looks like the only other plugin that uses `VoteActionParams` is the Llama one, so hopefully wouldn't be too bad to update their test files to accommodate this schema update either.

**Comment by Quazia** [comment]
@seanmc9 Is it possible to use the [project](https://github.com/rabbitholegg/questdk-plugins/pull/308/files#diff-d9c3b5f3c46529e88081e868944bc351ded1a4b66e49ebfa6adb72fb5c65da19R83) param instead of the add contract address? I think the `numVotes` works. Maybe `weight` would be another name option.

**Comment by seanmc9** [comment]
@Quazia Oh yes, absolutely, great call! Didn't know if `project` was a reserved param in y'all's system since it's so prevalant, but if that could serve as the contract address that'd be great! And yeah, `weight` works too name-wise!

**Comment by seanmc9** [comment]
@Quazia updated! does this structure look good to flesh out the tests for?

**Comment by Quazia** [comment]
@seanmc9 Yes it looks great! Sorry for the delay.

**Comment by seanmc9** [comment]
@Quazia no worries!

**Comment by seanmc9** [comment]
@Quazia Alrighty, just updated the rest of the files! Does everything look good here/ready to merge?

**Comment by mmackz** [comment]
Can you bring in the latest changes from our main branch and regen the lockfile. There is a few conflicts.

**Comment by mmackz** [comment]
You will also need to generate a changeset. Run the changeset command from root and follow the instructions.

`pnpm changeset`

**Comment by seanmc9** [comment]
@mmackz done!

**Comment by seanmc9** [comment]
@Quazia @mmackz just pinging here again to see if there's anything else that's needed!

**Pull request closed without merging**
