### PR TITLE
Update token-addresses.ts

### PR DESCRIPTION
**Pull request by MackeDev**
Add MACKE to Uniswap plugin (Ethereum Chain)

Discussed and approved with @zeck8298

Please give me a heads up if any additional changes need to be made.

Thanks,
MackeDev

### CODE REVIEW

**Comment by MackeDev** [comment]
Updated changeset

**Comment by Quazia** [comment]
@MackeDev Just confirmed with the team - I'm getting this merged now. Should be released to prod early next week and I'll let you know when it is. Thank you for your contribution!

**Comment by MackeDev** [comment]
> @MackeDev Just confirmed with the team - I'm getting this merged now. Should be released to prod early next week and I'll let you know when it is. Thank you for your contribution!

Thank you Quazia. Excited!

**Comment by MackeDev** [comment]
> @MackeDev Just confirmed with the team - I'm getting this merged now. Should be released to prod early next week and I'll let you know when it is. Thank you for your contribution!

Just checking in on this one.

**Comment by mmackz** [comment]
> > @MackeDev Just confirmed with the team - I'm getting this merged now. Should be released to prod early next week and I'll let you know when it is. Thank you for your contribution!
> 
> Just checking in on this one.

Sorry for the delay, will get this merged right now. 🫡

**Review by mmackz — APPROVED** [review]

**Comment by MackeDev** [comment]
> > > @MackeDev Just confirmed with the team - I'm getting this merged now. Should be released to prod early next week and I'll let you know when it is. Thank you for your contribution!
> > 
> > 
> > Just checking in on this one.
> 
> Sorry for the delay, will get this merged right now. 🫡

No worries, thanks for getting this in.

Is there any estimation for when it'll go live?

**Pull request merged**
