### PR TITLE
fix(camelot): address issues with amount recognition and enhance testing logic

### PR DESCRIPTION
**Pull request by mmackz**
## Summary
This PR addresses a minor issue related to amount recognition within the Camelot plugin and enhances the logic for testing by re-iterating on the previous patterns. It also includes additional test cases to ensure robustness and reliability.

## Changes
- Added Ether to the list of recognized tokens.
- Improved logic to handle ETH transactions accurately.
- Refined testing patterns from previous implementations.

## Bug Fixes
- Fixed an issue where `amountIn` was not being recognized properly.

## Testing
- Expanded test coverage to include all available parameters.
- Added new test cases to make sure the correct filter is created for ETH specific scenarios.
- Ensured all existing tests pass with the new changes.

### CODE REVIEW

**Comment by mmackz** [comment]
Removed some tokens from the supported token list which have no available trading routes.

**Review by Quazia — APPROVED** [review]
LGTM - what are the addresses you removed from the `DEFAULT_TOKEN_LIST`?

**Comment by mmackz** [comment]
> LGTM - what are the addresses you removed from the `DEFAULT_TOKEN_LIST`?

Went and manually tested all the tokens on the UI and there was a few which were not able to be traded on V2 due to low or no liquidity. The following tokens were removed:

- 0x17FC002b466eEc40DaE837Fc4bE5c67993ddBd6F - FRAX (No route found)
- 0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0 - UNI (No route found)
- 0xf97f4df75117a78c1A5a0DBb814Af92458539FB4 - LINK (extremely low liquidity)

**Comment by mmackz** [comment]
Should we also add GRAIL? It is the native token for the camelot dex. I overlooked this earlier, but had planned to add it.

**Comment by Quazia** [comment]
> Should we also add GRAIL? It is the native token for the camelot dex. I overlooked this earlier, but had planned to add it.

Yeah let's do then we can get this in

**Pull request merged**
